apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dani-nginx
spec:
  replicas: 3
  template:
   metadata:
     labels:
       app: dani-nginx
   spec:
     containers:
     - name: dani-nginx
       image: https://registry.hub.docker.com/damaratx/dani-nginx
       ports:
       - containerPort: 8080

kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: maintest
      protocol: TCP
      port: 80
      targetPort: 80
